#ifndef __logging_hpp__
#define __logging_hpp__

#define SPDLOG_ACTIVE_LEVEL SPDLOG_LEVEL_DEBUG

#include <spdlog/spdlog.h>
#define NLOG_TRACE SPDLOG_TRACE
#define NLOG_DEBUG SPDLOG_DEBUG
#define NLOG_INFO SPDLOG_INFO
#define NLOG_WARN SPDLOG_WARN
#define NLOG_ERROR SPDLOG_ERROR

#define NLOG_LOGGER_TRACE SPDLOG_LOGGER_TRACE
#define NLOG_LOGGER_DEBUG SPDLOG_LOGGER_DEBUG
#define NLOG_LOGGER_INFO SPDLOG_LOGGER_INFO
#define NLOG_LOGGER_WARN SPDLOG_LOGGER_WARN
#define NLOG_LOGGER_ERROR SPDLOG_LOGGER_ERROR
#define NLOG_LOGGER_CRITICAL SPDLOG_LOGGER_CRITICAL

#endif